# Generated by Django 2.0.13 on 2019-12-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masege',
            name='fazer',
            field=models.IntegerField(default=0),
        ),
    ]
